# Generated by Django 2.0.2 on 2018-03-26 00:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=32)),
                ('date', models.DateField(auto_now=True)),
                ('img', models.ImageField(blank=True, default='.static/photo.png', upload_to='', verbose_name='Фото')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='Тег')),
                ('slug', models.SlugField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Tags'),
        ),
    ]
